//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.TestStudio.Jira.BugTracking {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class JiraTrackerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static JiraTrackerSettings defaultInstance = ((JiraTrackerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new JiraTrackerSettings())));
        
        public static JiraTrackerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection MruServers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MruServers"]));
            }
            set {
                this["MruServers"] = value;
            }
        }
    }
}
